### ISSUE TITLE
Support Sublime Text 3

### ISSUE THREAD

**Issue by oakmac** [oakmac/sublime-text-parinfer#10]
I have only tested this plugin against Sublime Text 2. Need to make sure it works well for both ST2 and ST3.

**Comment by JoakimLofgren** [comment]
I've been playing around with this on a Windows machine

I have pushed a [WIP branch](https://github.com/JoakimLofgren/sublime-text-parinfer/tree/windows-fixes).

**Comment by JoakimLofgren** [comment]
nvm.. maybe I should have checked the pull requests first :P

**Comment by JoakimLofgren** [comment]
I assume this can be closed now?

**Comment by oakmac** [comment]
Yes :)
