### ISSUE TITLE
Pure Python implementation

### ISSUE THREAD

**Issue by leonid-shevtsov** [oakmac/sublime-text-parinfer#15]
Hi,

seeing as you are the author of parinfer for Atom, I guess your goal is to reuse JS/CLJS code from there, but a pure Python implementation has some important benefits in a Sublime Text plugin.

I've decided to make the latter when seeing the parinfer algorithm, but then I saw your plugin and I think that two competing plugins is really bad, so what do you think if I make a python implementation right here, in replacement of the node.js proxy? Does it make sense for you, too?

**Comment by oakmac** [comment]
I would absolutely love this!

I'm sitting at the airport right now, and will add some more thoughts to
this issue when I have a chance.

**Comment by shaunlebron** [comment]
@leonid-shevtsov great!  I'll work on making the tests available in a simpler format since that'll help verify your port.

using either of these libs might make it easier to make a direct port of clojure idioms:
- [fn.py](https://github.com/kachayev/fn.py)
- [pyrsistent](https://github.com/tobgu/pyrsistent)

**Comment by oakmac** [comment]
Now that I'm not sitting in an airport I just wanted to reiterate how good of an idea I think this is.

This plugin is the first Python I have ever written so I wanted to keep the complexity to a minimum and not implement the Parinfer algorithm (which is non-trivial) in a language I had zero experience in. Having a native Python implementation would be much cleaner (and probably faster) than the Python <--> Node.js code.

I'm not completely opposed to putting the code for it directly into this repo, but it also might be a good idea to have a separate repo for the Parinfer library (then this project can just depend on it - however that works in Python). The Parinfer algorithm is a pretty well-defined problem and as Shaun mentioned already comes with a pretty comprehensive set of tests to develop against.

Would be really happy to see this happen :)

**Comment by oakmac** [comment]
https://github.com/oakmac/parinfer.py
