### ISSUE TITLE
prevent extra indentations

### ISSUE THREAD

**Issue by ItamarShDev** [oakmac/sublime-text-parinfer#32]
For some reason, when using objects, the indentations needed for the Parinfer is very deep
E.g.

```
cabin/cabine {
                    :shared {
                              :test? (? $scope.mode.test)
                              :routing-data (when (? $scope.mode.test) (js->clj (? $scope.test.yaml.routing) :keywordize-keys true))
                              :comparative? (when (? $scope.history) (boolean (? $scope.history.originalTest)))}

                    :target target} 
```

instead of:

```
cabin/cabine {
   :shared {
      :test? (? $scope.mode.test)
      :routing-data (when (? $scope.mode.test) (js->clj (? $scope.test.yaml.routing) :keywordize-keys true))
      :comparative? (when (? $scope.history) (boolean (? $scope.history.originalTest)))}

   :target target}
```

**Comment by oakmac** [comment]
The example you gave is expected behavior for [Paren Mode](https://shaunlebron.github.io/parinfer/#paren-mode).

I assume this is happening when you first open a file using atom-parinfer?

**Comment by ItamarShDev** [comment]
Yes.
Also sublime-parifner makes a mess if I don't follow this pattern.
So this is expected behavior?

**Comment by oakmac** [comment]
> So this is expected behavior?

Yes.

This is the core Parinfer algorithm working as expected: adjusting indentation to match paren structure. If you have not already, you might want to give the [main Parinfer site](https://shaunlebron.github.io/parinfer/) a read for a thorough explanation of how and why the algorithm works the way it does.

[Issue #46](https://github.com/oakmac/atom-parinfer/issues/46) and [Issue #51](https://github.com/oakmac/atom-parinfer/issues/51) from the atom-parinfer repo might also be helpful.
