### ISSUE TITLE
Sublime Text 3 - Parinfer is not working.

### ISSUE THREAD

**Issue by niconc** [oakmac/sublime-text-parinfer#34]
Hello Chris,

I've just installed parinfer in ST 3 and it's not working at all.
I've opened the settings file in order to add `".lisp"` extension and ST3 don't let me even edit the file.

I've also try to enable Parinfer using `cmd+(` with no result.

Any ideas?

Thank you.

**Comment by laconiccrafts** [comment]
Works on my machine. There must be something else going on.

**Comment by bmix** [comment]
> I've opened the settings file in order to add `".lisp"` extension and ST3 don't let me even edit the file.

Could it be, that you tried to edit the global settings instead of the user settings? That one is write-protected.
