### ISSUE TITLE
add to Package Control

### ISSUE THREAD

**Issue by oakmac** [oakmac/sublime-text-parinfer#4]
Need to read about how [Package Control](https://packagecontrol.io/) works and add this to it.

**Comment by oakmac** [comment]
Here are the steps: https://packagecontrol.io/docs/submitting_a_package

**Comment by oakmac** [comment]
Here is the Pull Request: https://github.com/wbond/package_control_channel/pull/5079

**Comment by shaunlebron** [comment]
:+1:

**Comment by oakmac** [comment]
The PR has been merged :)
