### ISSUE TITLE
In 1.0.0, debug logging is enabled

### ISSUE THREAD

**Issue by oconnor0** [oakmac/sublime-text-parinfer#45]
It looks like in the 1.0.0 release that debug logging is enabled. I get the following in the Sublime console:

```
DEBUG: File has been loaded, but do not start Parinfer
```

Is there a configuration option to disable this? I didn't see one.

**Comment by oakmac** [comment]
> Is there a configuration option to disable this? I didn't see one.

Nope - this is a straight up bug. I will fix and publish a new version today 👍 

Good catch!

**Comment by oakmac** [comment]
Published v1.1.0 with the fix

**Comment by oconnor0** [comment]
Oh, awesome, thanks!
