### ISSUE TITLE
Status of project?

### ISSUE THREAD

**Issue by StarScape** [oakmac/sublime-text-parinfer#48]
@oakmac I'm curious about the status and the maturity of this project. I notice it hasn't been updated in a year but that doesn't necessarily mean anything if the project is stable. Is it usable as a daily driver? I'd really like to switch away from VSCode + Calva in favor of ST + Clojure Sublimed + this plugin.

Thanks!

**Comment by oakmac** [comment]
I use Sublime Text + this plugin + Clojure Sublimed near daily with no issues.

This plugin only implements Parinfer's "Indent Mode" (ie: not "Smart Mode"), but that doesn't really bother me in practice.

**Comment by StarScape** [comment]
That’s awesome to hear. Thanks for your quick reply, really looking forward to giving this a shot.
